apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: chachkies-upload
build:
  artifacts:
  - image: chachkies-upload
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yaml
    - kubernetes/service.yaml
