openapi: 3.0.1
info:
  title: App Accelerator API
  description: 'App Accelerator demo for OpenApi Projects'
  termsOfService: https://docs.vmware.com/en/Application-Accelerator-for-VMware-Tanzu/0.1/acc-docs/GUID-index.html
  contact:
    email: ashumilov@vmware.com
  license:
    name: Some Top Secret License
    url: http://microsamples.io/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://microsamples.io/api/operators
tags:
  - name: chachkie
    description: Chachkies
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /chachkies/{chachkieId}:
    get:
      tags:
        - chachkie
      summary:
        "Chachkie from S3 Bucket"
      operationId: "getChachkie"
      parameters:
        - name: chachkieId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File from S3 bucket
          content:
            application/pdf:
              schema:
                type: string
                format: binary

  /chachkies:
    post:
      tags:
        - chachkie
      summary:
        Load new chachkies
      operationId: loadChachkies
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                # 'file' will be the field name in this multipart request
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceMeta"
    get:
      tags:
        - chachkie
      summary: Find all chachkies
      description: Returns All Chachkies
      operationId: getChachkies
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelApiException"
components:
  schemas:
    ResourceMeta:
      type: object
      properties:
        size:
          type: number
        path:
          type: string
    Chachkie:
      type: object
      properties:
        id:
          type: string
          description: Object id
        latitude:
          type: number
          description: Latitude
        longitude:
          type: number
          description: Longitude
    ModelApiException:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string